---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lamanifest
  labels:
    app: hello
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
<<<<<<< HEAD
        image: linuxacademycontent/gitops:hellov1.2.1
=======
        image: linuxacademycontent/gitops:hellov1.2
>>>>>>> parent of 17766d6 (Auto-release linuxacademycontent/gitops:hellov1.2.2)
